feat: Add Sentry
yearn/yearn-api pull request #39
Opened 2022-02-04 06:54 UTC by phillip055

Sentry will help us capture errors and increase visibility.

2022-02-09 18:48 UTC, numan requested changes
Great work! Just added some minor feedback

2022-02-09 18:48 UTC, numan commented on app.mjs
> +    environment: process.env.NODE_ENV || "development"
Can we add both of these to `.env.example` ?

Also document it in the README?

2022-02-09 18:48 UTC, numan commented on app.mjs
> +  Sentry.init({
Also, can we make this optional? We don't necessarily want sentry running  in a dev environment

2022-02-09 18:48 UTC, numan commented on package.json
> +    "sentry-testkit": "^3.3.7",
Can we move this into dev dependencies and update the lock file?

2022-02-09 18:50 UTC, numan commented
closes https://github.com/yearn/yearn-api/issues/32

2022-02-14 17:12 UTC, phillip055 commented
@numan made some requested changes, thanks for being patient :)

2022-02-14 21:36 UTC, numan requested changes
@phillip055 looks good. Just a couple more very minor things

2022-02-14 21:36 UTC, numan commented on app.mjs
> +  Sentry.init({
Can you please run this file through `prettier`? Just making sure we have consistent styling

2022-02-14 21:36 UTC, numan commented on app.mjs
> +    });
Looks good. I think we just need to add a `reply.send(error)` here so it actually returns a 5xx response. As it is right now, it actually returns a 400 response.

This is going to throw off our monitoring tools

2022-02-14 22:08 UTC, numan commented
related to: https://github.com/yearn/yearn-api-infra/pull/2

2022-02-14 22:13 UTC, numan commented
@phillip055 I'm actually going to merge this in and address my feedback in a followup PR

2022-02-14 22:14 UTC, numan approved these changes

2022-02-14 22:14 UTC, merged